language: ruby
before_install:
  - gem install bundler
bundler_args: --without debugger
script: bundle exec rake spec
rvm:
  - ruby-head
  - 3.0.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - rbx-19mode
  - rbx-18mode
  - jruby-head
  - jruby-19mode
  - jruby-18mode
  - ree
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby-2.0.0
    - rvm: ruby-1.9.2
    - rvm: rbx-19mode
    - rvm: rbx-18mode
    - rvm: jruby-head
    - rvm: jruby-19mode
    - rvm: jruby-18mode
    - rvm: ree
notifications:
  email:
    recipients:
      - ngiger@ywesee.com
      - yasaka@ywesee.com
      - zdavatz@ywesee.com
