language: ruby
before_install:
  - gem install bundler
bundler_args: --without debugger
script: bundle exec rake spec
rvm:
  - ruby-head
  - 3.0
  - 2.7
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email:
    recipients:
      - ngiger@ywesee.com
      - yasaka@ywesee.com
      - zdavatz@ywesee.com
